### PR TITLE
Additional commands

### LINKED ISSUE #6: Additional commands
Can you please add support for buildah tag?

In addition can you please support --build-arg on buildah bud?

### PR DESCRIPTION
**Pull request by naude-r**
- add support for buildah tag
- allow optional build-arg to be specified for buildah bud

fixes #6 

Kindly review the new features added @dev-gaur @rohanKanojia .

### CODE REVIEW

**Review by rohanKanojia — COMMENTED** [review]
Looks good, Could you please add some tests to validate these new improvements?

**Comment by naude-r** [comment]
@rohanKanojia yes. currently there are no test cases for any commands. if PR #5 can be merged it would provide a base to add tests.

if not, it is fine. can add something specific for the changes made.

**Comment by rohanKanojia** [comment]
@naude-r : okay, let me merge this so that you can add some tests

**Comment by naude-r** [comment]
@rohanKanojia thank you! will open a new PR for the test cases.

**Pull request merged**
